### PR TITLE
Fixes validation message fields don't update JSON window correctly

### LINKED ISSUE #24: Entering text into second validation component doesn't update JSON
## Steps to reproduce
1. Open up the authoring prototype.
2. By default there will be 2 responses
3. Enter text into the validation message on the second response.

## Expected behaviour
Text appears in the validation message field and JSON is updated.

## Actual behaviour
Text doesn't appear in the validation message field and JSON isn't updated.

## Screenshot
validation-message

### PR DESCRIPTION
**Pull request by samiwel**
## Description
Fixes #24.
Validation message component on subsequent answers doesn't update the JSON schema.

## How to test
Modify the default JSON so that it includes multiple answers.
Enter text in both validation message fields and observe that the JSON updates appropriately.

### CODE REVIEW

File: src/components/ResponseFields/index.js [hunk 1]
```diff
@@ -48,6 +48,9 @@ export default class ResponseFields extends Component {
     const {id, mandatory, guidance, options, description, ...otherProps} = this.props.response
     const validationMessage = otherProps.validation.messages.MANDATORY
 
+    const validationName = 'answers.{index}.validation.messages.MANDATORY'
```
Comment (hamishtaplin) [inline src/components/ResponseFields/index.js]: Use template strings here instead:

```javascript
const validationName = `answers.${this.props.responseIndex}.validation.messages.MANDATORY`
```

Comment (samiwel) [inline src/components/ResponseFields/index.js]: 👍 I was looking for a way to do just that!
